### PR TITLE
Uml diagram

### PR DESCRIPTION
**Pull request by Vicx95**

### CODE REVIEW

**Review by ziobron — COMMENTED** [review]
Please add a png file and add it to README

**Comment by Vicx95** [comment]
> Please add a png file and add it to README

done

**Review by bartosz-gruszczyk — APPROVED** [review]
Looks good to me

**Comment by ziobron** [comment]
Thanks @bartosz-gruszczyk for Code Review.
🏅 1 XP granted

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @Vicx95 for making course materials better!

**Pull request merged**
