### PR TITLE
Add code guideliness and remove redundant gitignore file

### PR DESCRIPTION
**Pull request by Vicx95**

### CODE REVIEW

**Review by iprice73 — APPROVED** [review]
second rule: m_counter and I'm happy 😅

**Comment by ziobron** [comment]
Thanks @iprice73 for Code Review.
🏅 1 XP granted

**Comment by Vicx95** [comment]
> second rule: m_counter and I'm happy 😅

done

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @Vicx95 for making course materials better!

**Pull request merged**
